### ISSUE TITLE
Some of the Talents don't work due to the AdvancedEffects not being correct.

### ISSUE THREAD

**Issue by CaptainClutch64** [AdvancedPlugins/Skills#1]
### Describe the bug

![image](https://github.com/user-attachments/assets/dab6b016-73d5-4f5d-838d-9b8bf9f0f283)

[13:13:26 WARN]: [AdvancedSkills] 4Failed to activate effect 'fMULTIPLY_DROPS:2'
[13:13:26 WARN]: [AdvancedSkills] cAdditional information: 7Failed to activate effects as advancedEffect is null or invalid: 'MULTIPLY_DROPS', MULTIPLY_DROPS:2, trigger:MINING, entity:CaptainCLutch_64

This is the error my console produces. 
The 3x3 Trencher works just fine. The double-drop Talent doesn't though it seems. 

### How to reproduce

I can reproduce this by simple activating the "Double Drops" Talent.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/5ed098d7-586d-4f11-b1da-a3977008930f)

### Server Log

https://mcpaste.io/dd606aaaec685e64

**Comment by CaptainClutch64** [comment]
Please Ignore this as I found the issue. 
I apologize for submitting this without looking more into it.

The "MULTIPLY_DROP:2" was wrong according to your AdvancedPlugins Wiki. I had to change a few of the Talents to "MORE_DROPS:2 instead.

**Comment by GC-spigot** [comment]
Sorry about that problem! Seems like cloud storage we use somehow reverted as we initially fixed this already, thanks for the report!
