### ISSUE TITLE
ERROR on startup 1.21

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#10]
### Describe the bug

16.08 14:23:48 [Server] INFO nutmegofaxomine sent CLICK_WINDOW (734.981ms) (1320 bytes) B=1 v=Optional[1] L=40 O=0 e=Optional.empty D=PICKUP c=Optional[{40=ItemStack[null]}] W=[type=minecraft:ender_chest] a=123890514938045 
16.08 14:23:50 [Server] INFO Saved 4 name changes to the database.
16.08 14:23:55 [Server] ERROR Could not pass event PlayerSwapHandItemsEvent to AdvancedSkills v1.0.0
16.08 14:23:55 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 30 out of bounds for length 30
16.08 14:23:55 [Server] INFO at AdvancedSkills-1.0.3.jar/net.advancedplugins.skills.menus.TalentsMenu.openInventory(TalentsMenu.java:75) ~[AdvancedSkills-1.0.3.jar:?]
16.08 14:23:55 [Server] INFO at AdvancedSkills-1.0.3.jar/net.advancedplugins.skills.listeners.ItemSwitchListener.onSwitch(ItemSwitchListener.java:17) ~[AdvancedSkills-1.0.3.jar:?]
16.08 14:23:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
16.08 14:23:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
16.08 14:23:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
16.08 14:23:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
16.08 14:23:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1801) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
16.08 14:23:55 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
16.08 14:23:57 [Server] INFO nutmegofaxomine issued server command: /skills
16.08 14:23:59 [Server] WARN Invalid skill name: repair in class: Mage
16.08 14:23:59 [Server] WARN Invalid skill name: salvage in class: Mage
16.08 14:23:59 [Server] WARN Invalid skill name: taming in class: Mage
16.08 14:23:59 [Server] WARN Invalid skill name: smelting in class: Mage
16.08 14:23:59 [Server] WARN Invalid skill name: unarmed in class: Warrior
16.08 14:23:59 [Server] WARN Invalid skill name: taming in class: Warrior
16.08 14:23:59 [Server] WARN Invalid skill name: taming in class: Ranger
16.08 14:23:59 [Server] WARN Invalid skill name: repair in class: Craftsman
16.08 14:23:59 [Server] WARN Invalid skill name: smelting in class: Craftsman
16.08 14:23:59 [Server] WARN Invalid skill name: swimming in class: Explorer

### How to reproduce

Start server look in startup

**Comment by GC-spigot** [comment]
Too many skills not enough slots. We'll have a warning instead for next versions.

**Comment by Cryptics1999** [comment]
Oh I havent added any skills tho only talents
________________________________
Fra: GC ***@***.***>
Sendt: fredag 16. august 2024 21:40
Til: AdvancedPlugins/Skills ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [AdvancedPlugins/Skills] ERROR on startup 1.21 (Issue #10)


Too many skills not enough slots. We'll have a warning instead for next versions.

**Comment by GC-spigot** [comment]
Might be talents, probably is. Unsure from error. Yeah it's trying to get 31st talent's slot. So not enough talent slots.

**Comment by Cryptics1999** [comment]
Ok, so next version will add a second page for talents if you go over 29 since by default there is 1 ugly placed one below the squared formation?

________________________________
Fra: GC ***@***.***>
Sendt: fredag 16. august 2024 21:45
Til: AdvancedPlugins/Skills ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [AdvancedPlugins/Skills] ERROR on startup 1.21 (Issue #10)


Might be talents, probably is. Unsure from error. Yeah it's trying to get 31st talent's slot. So not enough talent slots.

**Comment by GC-spigot** [comment]
Also added pages!
