### ISSUE TITLE
Mana still dropping while disabled

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#11]
### Describe the bug

![image](https://github.com/user-attachments/assets/c2d2202d-2d53-489c-ac3a-f8d9ce4effed)
I have mana disabled in config

![image](https://github.com/user-attachments/assets/3852bf1c-c9ae-4102-b4f3-d6503e6e5775)

Still spawning while mining

### How to reproduce

1.21
Purpur
newest skill version
Have mana drops disabled
Mine blocks
still dropping

**Comment by GC-spigot** [comment]
Fixed
