### ISSUE TITLE
Data Breakage

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#13]
### Describe the bug

0.08 23:05:40 [Server] ERROR Could not pass event PlayerInteractEvent to AdvancedSkills v1.0.0
20.08 23:05:40 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "net.advancedplugins.skills.data.PlayerData.getActiveTalents()" is null
20.08 23:05:40 [Server] INFO at AdvancedSkills-1.0.5.jar/net.advancedplugins.skills.skills.SkillsHandler.getForTrigger(SkillsHandler.java:161) ~[AdvancedSkills-1.0.5.jar:?]
20.08 23:05:40 [Server] INFO at AdvancedSkills-1.0.5.jar/net.advancedplugins.skills.abilities.SkillsAbilitiesReader.getRawAbilities(SkillsAbilitiesReader.java:35) ~[AdvancedSkills-1.0.5.jar:?]
20.08 23:05:40 [Server] INFO at AdvancedSkills-1.0.5.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecutionBuilder.build(ActionExecutionBuilder.java:91) ~[AdvancedSkills-1.0.5.jar:?]
20.08 23:05:40 [Server] INFO at AdvancedSkills-1.0.5.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:73) ~[AdvancedSkills-1.0.5.jar:?]
20.08 23:05:40 [Server] INFO at AdvancedSkills-1.0.5.jar/net.advancedplugins.skills.impl.commons.effects.mechanics.triggers.internal.RightClickTrigger.onPlayerInteract(RightClickTrigger.java:47) ~[AdvancedSkills-1.0.5.jar:?]
20.08 23:05:40 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor477.execute(Unknown Source) ~[?:?]
20.08 23:05:40 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
20.08 23:05:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
20.08 23:05:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
20.08 23:05:40 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2017) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
20.08 23:05:40 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

Make a slight mistake in a talent, and for the plugin to suddenly not work at all. Fix mistake and now the plugin has gone all crazy and dont want to do anything even tho its fixed as data is broken

This issue accually is so annoying it makes the plugin unusable as my data get corrupted all the fucking time

**Comment by GC-spigot** [comment]
Solved the error!

**Comment by Cryptics1999** [comment]
Hey. I just tested it out. Most errors are gone but now im only getting this one

22.08 08:13:35 [Server] ERROR Command exception: /skills
22.08 08:13:35 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.set(long)" because "this.p" is null
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.data.PlayerData.updateLastAccessed(PlayerData.java:125) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.data.PlayerData.getSkillProgress(PlayerData.java:120) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.menus.SkillsMenu.openInventory(SkillsMenu.java:42) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.commands.impl.main.SkillsCommand.onExecute(SkillsCommand.java:40) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.impl.utils.commands.ConfigCommand.middleMan(ConfigCommand.java:91) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.impl.utils.commands.CommandBaseNew.onCommand(CommandBaseNew.java:99) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at AdvancedSkills-1.0.6.jar/net.advancedplugins.skills.impl.utils.commands.CommandBaseNew$1.execute(CommandBaseNew.java:48) ~[AdvancedSkills-1.0.6.jar:?]
22.08 08:13:35 [Server] INFO at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
22.08 08:13:35 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
________________________________
Fra: GC ***@***.***>
Sendt: torsdag 22. august 2024 09:17
Til: AdvancedPlugins/Skills ***@***.***>
Kopi: Cryptics1999 ***@***.***>; Author ***@***.***>
Emne: Re: [AdvancedPlugins/Skills] Data Breakage (Issue #13)


Solved the error!
