### ISSUE TITLE
The AdvencedSkills' API doesn't work

### ISSUE THREAD

**Issue by t-trv** [AdvancedPlugins/Skills#14]
### Describe the feature

![image](https://github.com/user-attachments/assets/e3d0b82e-9629-4a91-b1fa-976e7a568531)
Please help me to use the API with TAB plugin and EssentialsChat.

**Comment by GC-spigot** [comment]
Do you have PlaceholderAPI installed? It works fine for us, try this command
![image](https://github.com/user-attachments/assets/ac0af04e-9051-4fa3-be47-e79beea570e2)
It's working and displaying 0 as expected (I have 0 mana)
