### ISSUE TITLE
The Effect doesn't work

### ISSUE THREAD

**Issue by t-trv** [AdvancedPlugins/Skills#15]
### Describe the bug

Please help

### How to reproduce

You can see, the effect doesn't work

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/4a8cd1f5-28b5-4cd8-b176-65a69d1d79d6)

**Comment by Cryptics1999** [comment]
Change it to MORE_DROPS:2

**Comment by GC-spigot** [comment]
Fixed next update!
