### ISSUE TITLE
Shift F

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#18]
### Describe the bug

Shift F works for me to open Talents but not for players

### How to reproduce

Shift F works for me to open Talents but not for players

**Comment by Ynverxe** [comment]
Do you get an error?

**Comment by Cryptics1999** [comment]
No
Sendt fra min iPhone

29. aug. 2024 kl. 16:56 skrev Ynverxe ***@***.***>:

﻿

Do you get an error?

**Comment by Ynverxe** [comment]
Can you send me your plugin list?
