### ISSUE TITLE
%mana-cap% isn't a valid placeholder

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#20]
### Describe the bug

when receiving the message "you have received the maximum mana cap of %mana-cap% when at max mana, it displays a invalid placeholder

### How to reproduce

get max mana and check the chat popup

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/38c8a32a-d1bb-4256-b999-bdb4c9cd5090)

**Comment by Ynverxe** [comment]
Try editing your lang file and using %max_mana% instead of %mana_cap%. This will be fixed on next version and the placeholder will continue to be mana_cap

**Comment by moonies44** [comment]
> Try editing your lang file and using %max_mana% instead of %mana_cap%. This will be fixed on next version and the placeholder will continue to be mana_cap

i have gone through all my files and can't find mana_cap anywhere, you stated above it will be fixed to max_mana but will continue to be mana_cap, please can you be a bit more clear the placeholder i should be using on which file? thank you.
