### ISSUE TITLE
decrease_damage does nothing

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#25]
### Describe the bug

using default skill iron_skin, it simply doesn't activate. (got hit over 300 times with a 25% chance, doesnt work)

# Iron Skin talent
name: "Iron Skin"
description: "Chance to reduce incoming damage by 25%"
icon:
  type: IRON_CHESTPLATE

mana: 6

abilities:
  DEFENSE:
    cooldown: 10 # seconds
    chance: 25
    effects:
      - DECREASE_DAMAGE:25
      - PARTICLE:BLOCK_CRACK:10:0.3

### How to reproduce

enable skill and get attacked

**Comment by Ynverxe** [comment]
Hi! The correct way to do this is: `- DECREASE_DAMAGE:<random number>25</random number>`. You can also use a range like 15-50 to make it random.
