### ISSUE TITLE
Piercing skill doesn't work/activate

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#26]
### Describe the bug

as title, skill doesn't work/activate.

### How to reproduce

use "peircing" skill 

# Precise Shot talent
name: "Piercing"
description: "Chance for increased damage with bows, cooldown 8s"
icon:
  type: TARGET

# Mana cost increases with level
mana: 4

abilities:
  SHOOT:
    conditions:
      - '%item type% contains BOW : %allow%'
    effects:
      - INCREASE_DAMAGE:50
      - PARTICLE:CRIT:15:0.3 @Victim
      - PLAY_SOUND:ENTITY_ARROW_HIT_PLAYER:1:1.5 @Attacker

**Comment by Ynverxe** [comment]
Please, do not do that. We don't know what "doesn't work." What was the expected behavior of the effect? What was the behavior reproduced? How did you test it?

**Comment by moonies44** [comment]
sorry, i assumed because this was the default setup given by you in the plugin you would know this/how this one worked

so i used a bow against a zombie and skeleton up to 70 times, i didn't once get any increase in damage through shooting

expected behavoir was 50 damage on top, meaning a insta kill. i wasn't able to insta kill once, assumed it didn't work the from outcome

**Comment by Ynverxe** [comment]
Confirmed, working on it.

**Comment by Ynverxe** [comment]
UPDATE: This is not a bug, this is the expected behaviour of the "SHOOT" trigger. If you want to make it work with mobs use "SHOOT_MOB".

Here you have all the available triggers.
https://wiki.advancedplugins.net/abilities/triggers

**Comment by Ynverxe** [comment]
UPDATE: This is not a bug, this is the expected behaviour of the "SHOOT" trigger. If you want to make it working with mobs, use "SHOOT_MOB" instead of "SHOOT".

Here you have a list of all available triggers.
https://wiki.advancedplugins.net/abilities/triggers
