### ISSUE TITLE
Powerful shot talent does not activate

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#27]
### Describe the bug

the talent does not activate.

# Powerful Shot talent
name: "Powerful Shot"
description: "Chance to increase damage of crossbow shots by 25%, cooldown 10s"
icon:
  type: CROSSBOW

mana: 5

abilities:
  SHOOT:
    cooldown: 10
    conditions:
      - '%item type% contains CROSSBOW : %allow%'
    effects:
      - INCREASE_DAMAGE:25
      - PARTICLE:CRIT:10:0.3

### How to reproduce

use talent

**Comment by Ynverxe** [comment]
How did you test it?

**Comment by moonies44** [comment]
This was tested via hitting a zombie/skeleton with the crossbow 50 times. neither did the increase damage take effect nor did the particle crit to show it activated.

**Comment by Ynverxe** [comment]
If you want the talent to work with mobs use SHOOT_MOB.
https://wiki.advancedplugins.net/abilities/triggers
