### ISSUE TITLE
Impaler talent does nothing / dont activate

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#31]
### Describe the bug

# Impaler talent
name: "Impaler"
description: "Chance to deal extreme damage with melee trident hit"
icon:
  type: PRISMARINE_SHARD

mana: 4

abilities:
  ATTACK:
    cooldown: 30 # seconds
    chance: 25
    conditions:
      - '%attacker item type% contains TRIDENT : %allow%'
    effects:
      - INCREASE_DAMAGE:100
      - PARTICLE:CRIT:20:0.5
      - PLAY_SOUND:ENTITY_PLAYER_ATTACK_CRIT:1:1

### How to reproduce

use impaler talent that comes with the plugin

**Comment by Ynverxe** [comment]
How did you test it?

**Comment by moonies44** [comment]
To test this i threw a trident at a zombie 200 times, considering the damage increase in this it should insta kill, but in 200 tries, could not achieve a insta kill. Under this pretense, came to the conclusion this simply doesnt work

**Comment by Ynverxe** [comment]
This is not a bug, you are using the incorrect trigger. "ATTACK" will trigger the effect when you melee a player. You need to use "SHOOT_MOB" trigger.
