### ISSUE TITLE
Shield master talent does nothing / doesn't activate

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#32]
### Describe the bug

tested after 400 hits, nothing happens with default config

# Shield Master talent
name: "Shield Master"
description: "Negate all damage when blocking with a shield, cooldown 10s"
icon:
  type: SHIELD

mana: 8

abilities:
  SHIELD_BLOCK:
    cooldown: 10
    effects:
      - CANCEL_EVENT
      - PARTICLE:CRIT:15:0.5
      - PLAY_SOUND:ITEM_SHIELD_BLOCK:1:1

### How to reproduce

use the talent

**Comment by Ynverxe** [comment]
Hi! This should be fixed in the next version.
