### ISSUE TITLE
potent brew talent does nothing

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#33]
### Describe the bug

when using this talent, it activates but nothing happens

# Potent Brew talent
name: "Potent Brew"
description: "Chance to gain positive potion effects when consumed, cooldown 30s"
icon:
  type: GLOWSTONE_DUST

mana: 10

abilities:
  EAT:
    cooldown: 30
    conditions:
      - '%food type% contains POTION : %allow%'
    effects:
      - POTION:STRENGTH:1:300
      - POTION:HASTE:1:300
      - POTION:SPEED:1:300
      - PARTICLE:SPELL_MOB:20:0.5
      - PLAY_SOUND:ENTITY_WITCH_DRINK:1:1

### How to reproduce

use the talent and drink a potion

**Comment by Ynverxe** [comment]
I tested it and works as expected. Can you provide more information?
