### ISSUE TITLE
battle fury talent doesn't activate

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#34]
### Describe the bug

tried killing 50 times with a 25% chance but never activates

# Battle Fury talent
name: "Battle Fury"
description: "25% chance to gain Strength II after killing a player"
icon:
  type: BLAZE_POWDER

mana: 9

abilities:
  KILL_PLAYER:
    cooldown: 45 # seconds
    chance: 25
    conditions:
      - '%attacker item type% contains _SWORD : %allow%'
    effects:
      - POTION:INCREASE_DAMAGE:2:200
      - PARTICLE:FLAME:20:0.5
      - PLAY_SOUND:ENTITY_ENDER_DRAGON_GROWL:1:1

### How to reproduce

use talent and kill a player

**Comment by moonies44** [comment]
this was tested by killing my alt account 30 times, which took a while.
neither flame particle, or dragon sound effect played - after every kill checking if strength 2 was applied, to which it was not. at a 25% chance and 30 attempts, this should definitely have activated at least once, assumed not working due to outcome

**Comment by Ynverxe** [comment]
That's weird, works fine for me. Just for testing purposes you can set a higher chance and a low cooldown to verify it.
