### ISSUE TITLE
cleaving strike talent does nothing

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#35]
### Describe the bug

nothing happens with this skill active after testing

# Cleaving Strike talent
name: "Cleaving Strike"
description: "Chance to deal damage to nearby enemies on hit, cooldown 12s"
icon:
  type: IRON_AXE

mana: 5

abilities:
  ATTACK:
    conditions:
      - '%attacker item type% contains _AXE : %allow%'
    effects:
      - DO_HARM:3 @Aoe{r=10,t=damageable}
      - PARTICLE:SWEEP_ATTACK:30:0.5
      - PLAY_SOUND:ENTITY_PLAYER_ATTACK_SWEEP:1:1

### How to reproduce

activate talent, and kill a mob within 10 radius.

**Comment by Ynverxe** [comment]
Works fine for me. Just for testing purposes you can set a higher chance and a low cooldown to verify it.

**Comment by Ynverxe** [comment]
Use ATTACK_MOB instead of ATTACK.
https://wiki.advancedplugins.net/abilities/triggers
