### ISSUE TITLE
Mining skill does not work on several blocks

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#36]
### Describe the bug

the mining skill built in the game does not work with the blocks:

Deepslate
Deepslate Ores
Andesite

### How to reproduce

use mining skill on these blocks

**Comment by Ynverxe** [comment]
Works well for me. Anyway, while testing your issue I found a bug that causes skills to not reload when you use /skills reload.

Deepslate ores and Andesite doesn't works with the default configuration, you must to create a collection of deepslate ore types like %ore types% in abilities.yml and use them like they're used in mining.yml, [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html) you have a list of all available material types.
