### ISSUE TITLE
Unable to Create new classes

### ISSUE THREAD

**Issue by Dalt24** [AdvancedPlugins/Skills#41]
### Describe the bug

When attempting to create a new class or modify existing ones it throws an unexpected error. It looks like the class menu is bound to 5 slots

java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5

When modifying an existing class if you change the name it will generate the default class you deleted on next reload.

### How to reproduce

Adding a new class to the classes directory, or renaming one of the defaults to another name will cause the issue.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/0c03b59d-576f-4761-b20a-5399e7a787cc)
![image](https://github.com/user-attachments/assets/651b8a5a-9cd2-4266-9ff2-6957b06e3605)
![image](https://github.com/user-attachments/assets/323d30f6-cc32-473f-810f-64fc8ccf0bcd)

**Comment by Dalt24** [comment]
Found workaround - In classesMenu.yml you can add another slot. 
![image](https://github.com/user-attachments/assets/46271856-2792-41bb-9f13-2d882de9bb4e)

**Comment by Ynverxe** [comment]
Hi! I'll add an option on config.yml to choose if generate the default classes files or not.
