### ISSUE TITLE
/skills setclass [class] [player]  doesn't work

### ISSUE THREAD

**Issue by CraftingJon** [AdvancedPlugins/Skills#43]
### Describe the bug

We have a Problem with the Skill Plugin because the command: /skills setclass [class] [player]  doesn't work.

### How to reproduce

Pinguuu doesn't know how (He is my Dev)

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/835b927f-07a9-4a95-8307-93950174c486)

### Server Log

https://mcpaste.io/d52b6d1b1f7afcde

**Comment by Ynverxe** [comment]
Fixed! Wait for the next release!
