### ISSUE TITLE
Method not loaded! 'ITEMSTACK_SET_GLINT_OVERRIDE'

### ISSUE THREAD

**Issue by ghost** [AdvancedPlugins/Skills#44]
### Describe the bug

When I use the /skills command and go to the talents section I get this error in the console

### How to reproduce

When I use the /skills command and go to the talents section I get this error in the console

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/fc1f6b8c-0324-4895-a6a5-16ac7c9446bd)

### Server Log

https://mcpaste.io/31c0b209e7be76f9

**Comment by Ynverxe** [comment]
Outdated plugin version, current is 1.2.9
