### ISSUE TITLE
Reload problem

### ISSUE THREAD

**Issue by frknmrl** [AdvancedPlugins/Skills#45]
### Describe the bug

When I use the /askills reload command in the plugin, it does not reload the changes I made for the Party menu, the Name changes in the Skills. I have to turn the server off and on

### How to reproduce

When I use the /askills reload command in the plugin, it does not reload the changes I made for the Party menu, the Name changes in the Skills. I have to turn the server off and on

**Comment by Ynverxe** [comment]
Hi! This should be fixed in the next release!
