### ISSUE TITLE
Talent not fully function

### ISSUE THREAD

**Issue by hath19** [AdvancedPlugins/Skills#49]
### Describe the bug

Talent only detect one type of block from multiple condition.

![talent](https://github.com/user-attachments/assets/8c8e6185-6c9a-4b59-81d5-b03efbe57ece)

### How to reproduce

# Treasure Hunter talent
name: "Treasure Hunter"
description: "Chance to find rare items while digging"
icon:
  type: GOLD_NUGGET

mana: 6

abilities:
  MINING:
    cooldown: 1
    chance: 15      
    conditions:
      - '%item type% contains _SHOVEL : %allow%'
      - '%block type% contains DIRT|SAND|CLAY|GRAVEL|MYCELIUM : %allow%'          
    
    effects:
      - GIVE_ITEM:IRON_NUGGET:3
      - PARTICLE:COMPOSTER:10:0.5
      - PLAY_SOUND:ENTITY_EXPERIENCE_ORB_PICKUP:1:1
      
Talent effect only detect 1st block which is Dirt. 

There's no drop for Sand, Clay, Gravel & Mycelium.

**Comment by Ynverxe** [comment]
Hi! Fixed error, wait for the next update!
