### ISSUE TITLE
Skills do not work

### ISSUE THREAD

**Issue by kotorinet** [AdvancedPlugins/Skills#52]
### Describe the bug

The Skills dont work no matter what I do

### How to reproduce

Fix the Skills

### Screenshots / Videos

https://streamable.com/9j5jia

### Server Log

https://mcpaste.io/21868d343fff9325

**Comment by GC-spigot** [comment]
Fixed next update

**Comment by kotorinet** [comment]
Hey, its still not fixed with the 1.3.4 or will another update come?
