### ISSUE TITLE
Leveling/points not given 

### ISSUE THREAD

**Issue by Dev-W-Miller** [AdvancedPlugins/Skills#53]
### Describe the bug

No points are given for any skill, while running the current version of plugin 1.3.5 on 1.21.3 paper server… no error is given. 

No start up error is given either 

My plugin list is given below 

### How to reproduce

Do anything to get skill points naturally and it wont function.

### Screenshots / Videos

![IMG_0284](https://github.com/user-attachments/assets/0bedc1fe-a2a0-4f1c-ba14-20afc0b54671)

**Comment by Trevypants** [comment]
+1

**Comment by GC-spigot** [comment]
Looking into this!

**Comment by GC-spigot** [comment]
Solved! Update coming later today
