### ISSUE TITLE
Thunderbolt and Treasurehunter talent

### ISSUE THREAD

**Issue by SirJben** [AdvancedPlugins/Skills#54]
### Describe the bug

Default files lack proper target/effect.

- Treasurehunter has `DROP_ITEM` effect, which doesn't exist. It must be `GIVE_ITEM`.
- Thunderbolt lacks target. Add @Victim, `LIGHTNING:true @Victim`.

### How to reproduce

Default files

**Comment by GC-spigot** [comment]
Thanks jben<3 fixed it
