### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#7]
### Describe the bug

If you set a talent to be gotten at level 10, you dont get the talent before you get to level 11

### How to reproduce

1.21 Purpur
Level up to the designated level for a talent
You dont have it yet
Level up 1 more level
it is added

**Comment by GC-spigot** [comment]
Looking into it!

**Comment by Ynverxe** [comment]
Fixed! Wait for the next release.
